(()=>{
const $=id=>document.getElementById(id),TAX=.075,R=['common','uncommon','rare','epic','legendary','mythic'];
const fmt=c=>'$'+(Math.max(0,Math.round(c))/100).toFixed(2);
const ITEMS=[
['blue','skin','Blue Goo','common',0,'#69a9ff',1],['lime','skin','Toxic Lime','uncommon',1200,'#6ce87f'],['pink','skin','Bubble Gum','rare',3200,'#ff78c8'],['gold','skin','Gold Rush','epic',7200,'#ffd159'],['lava','skin','Lava Core','legendary',16500,'#ff754e'],['galaxy','skin','Galaxy Goo','mythic',38000,'#9a70ff'],['ice','skin','Frostbite','rare',3600,'#7ee7ff'],['voidskin','skin','Void Slime','mythic',46000,'#2b2850'],['cherry','skin','Cherry Pop','common',800,'#ff556f'],['chrome','skin','Chrome Blob','epic',8800,'#b7c7db'],['royal','skin','Royal Ooze','legendary',21000,'#6d49ff'],['angel','skin','Celestial Goo','mythic',50000,'#edf6ff'],
['dust','trail','Dust','common',0,'#7182a0',1],['spark','trail','Spark','uncommon',1350,'#65d9ff'],['money','trail','Mint Trail','rare',3100,'#67e7a8'],['rainbow','trail','Prism','epic',7600,'#c774ff'],['fire','trail','Inferno','legendary',15800,'#ff7255'],['void','trail','Void Wake','mythic',36500,'#795cff'],['frost','trail','Frost Trail','rare',3500,'#9eefff'],['bubbles','trail','Bubble Wake','common',850,'#74cfff'],['comet','trail','Comet Dust','rare',4300,'#ffcf73'],['glitch','trail','Glitch Steps','epic',9200,'#ff58d0'],
['none','charm','No Charm','common',0,'#61708a',1],['cube','charm','Crystal Cube','uncommon',1500,'#59d9ff'],['star','charm','Nova Shard','rare',3400,'#ffd15a'],['crown','charm','Royal Fragment','epic',8100,'#c579ff'],['orb','charm','Solar Orb','legendary',17200,'#ff7a54'],['black','charm','Singularity','mythic',42000,'#5d4bba'],['mint','charm','Mint Chip','rare',3900,'#69e8a9'],['pebble','charm','Lucky Pebble','common',750,'#a8a195'],['diamond','charm','Crown Diamond','legendary',22500,'#86ecff'],['aurora','charm','Aurora Core','mythic',48000,'#ff7de3']
].map(a=>({id:a[0],type:a[1],name:a[2],rarity:a[3],price:a[4],color:a[5],starter:!!a[6]}));
const CHESTS=[
{name:'Scrap Chest',price:150,c1:'#8e6b45',c2:'#523820',start:{1:86,2:10,3:3,4:.9,5:.1},tap:{1:22,2:12,3:6,4:2.5}},
{name:'Lucky Chest',price:450,c1:'#4fa868',c2:'#245b38',start:{1:65,2:23,3:8,4:3.5,5:.5},tap:{1:30,2:18,3:9,4:4}},
{name:'Royal Chest',price:900,c1:'#5877e7',c2:'#2e419c',start:{1:40,2:35,3:17,4:7,5:1},tap:{1:38,2:24,3:13,4:6}},
{name:'Crown Chest',price:1800,c1:'#d89a2e',c2:'#7e4a13',start:{1:18,2:38,3:28,4:13,5:3},tap:{1:48,2:32,3:18,4:9}}
];
const REWARD={1:{common:70,uncommon:25,rare:5,epic:0,legendary:0,mythic:0},2:{common:30,uncommon:45,rare:20,epic:5,legendary:0,mythic:0},3:{common:0,uncommon:20,rare:45,epic:28,legendary:6.5,mythic:.5},4:{common:0,uncommon:0,rare:20,epic:40,legendary:32,mythic:8},5:{common:0,uncommon:0,rare:0,epic:10,legendary:45,mythic:45}};
const css=document.createElement('style');css.textContent=`.bbTapSuccess{color:#69e8a9;font-weight:1000;text-shadow:0 0 12px #69e8a966}.bbTapFail{color:#ff7b8d;font-weight:1000}.bbRoll{animation:bbRoll .16s ease-in-out 5}@keyframes bbRoll{50%{transform:scale(1.14);filter:brightness(1.5)}}#chestTap,#chestReveal{margin-top:10px}.bbChestHint{font-size:10px;color:#8294b2;line-height:1.45}.bbOdds{display:grid;grid-template-columns:1fr auto;gap:3px 9px;font-size:10px;color:#aebbd1}.bbOdds b{color:#fff}`;document.head.appendChild(css);
function read(){const a=JSON.parse(localStorage.getItem('blob_blitz_pc_public')||'{}');a.money??=500;a.owned??=['blue','dust','none'];a.opened??=0;return a}
function write(a){localStorage.setItem('blob_blitz_pc_public',JSON.stringify(a));if($('balance'))$('balance').textContent=fmt(a.money);if($('owned'))$('owned').textContent=a.owned.length}
function weighted(map){let n=Math.random()*100,t=0;for(const [k,v] of Object.entries(map)){t+=+v;if(n<t)return k}return Object.keys(map).at(-1)}
function stars(n){return '★'.repeat(n)+'☆'.repeat(5-n)}
function preview(i){if(i.type==='skin')return `<div class="slime" style="--c:${i.color}"><i></i></div>`;if(i.type==='trail')return `<div class="trail" style="--c:${i.color}"><span></span><span></span><span></span></div>`;return `<div class="charm" style="--c:${i.color}"></div>`}
function ownerOn(){const b=$('ownerBtn');return b&&!b.classList.contains('hidden')}
function setupOpeningUI(){const big=$('bigChest');if(!$('tapStatus')){const st=document.createElement('div');st.id='tapStatus';st.className='sub';st.style='min-height:38px;font-size:13px;font-weight:900';big.after(st);const tap=document.createElement('button');tap.id='chestTap';tap.className='btn gold hidden';tap.textContent='TAP TO UPGRADE';st.after(tap);const rev=document.createElement('button');rev.id='chestReveal';rev.className='btn primary hidden';rev.textContent='REVEAL COSMETIC';tap.after(rev)}
$('chestTap').onclick=attempt;$('chestReveal').onclick=reveal;$('bigChest').onclick=()=>{if(active&&!$('chestTap').classList.contains('hidden'))attempt()};$('chestContinue').onclick=()=>location.reload()}
function renderChestShop(){const g=$('shopGrid');if(!g)return;g.innerHTML='';g.className='chestGrid';$('cartPanel')?.classList.add('hidden');$('chestInfo')?.classList.remove('hidden');if($('chestInfo'))$('chestInfo').innerHTML=`<h3>Lucky Chest Rules</h3><div class="sub">You buy a <b>chance</b>, not a star level. The chest rolls ★1–★5 immediately, then you get <b>4 taps max</b> to try to upgrade it.</div><div class="box" style="margin-top:10px"><small>IMPORTANT</small><b style="font-size:13px;margin-top:5px">Failed taps still count.</b><div class="note">Final stars decide the cosmetic rarity pool. ★5 is the jackpot tier.</div></div>`;
CHESTS.forEach((c,idx)=>{const d=document.createElement('div');d.className='chestCard';d.style.setProperty('--chest1',c.c1);d.style.setProperty('--chest2',c.c2);const total=c.price+Math.round(c.price*TAX),ss=Object.entries(c.start).map(([k,v])=>`<span>${stars(+k)}</span><b>${v}%</b>`).join(''),tt=Object.entries(c.tap).map(([k,v])=>`<span>${k}★ → ${+k+1}★</span><b>${v}%</b>`).join('');d.innerHTML=`<div class="name" style="font-size:18px">${c.name}</div><div class="chestIcon"><div class="miniChest"></div></div><div class="bbChestHint"><b>STARTING STAR CHANCE</b></div><div class="bbOdds">${ss}</div><div class="bbChestHint"><b>CHANCE PER UPGRADE TAP</b> · 4 taps max</div><div class="bbOdds">${tt}</div><div class="chestMeta"><span>1 cosmetic</span><span>+7.5% tax</span></div><button class="price">${ownerOn()?'OWNER FREE':fmt(c.price)+' · '+fmt(total)+' total'}</button>`;d.querySelector('button').onclick=()=>buy(idx,ownerOn());g.appendChild(d)})}
let active=null,busy=false;
function setStarUI(n){$('openStars').textContent=stars(n)}
function updateTap(){if(!active)return;const c=active.chest,n=active.star,l=active.left;setStarUI(n);if(n>=5){$('tapStatus').innerHTML='<span class="bbTapSuccess">★★★★★ MAX STAR CHEST</span>';$('chestTap').classList.add('hidden');$('chestReveal').classList.remove('hidden');return}if(l<=0){$('tapStatus').innerHTML=`NO TAPS LEFT · FINAL: <b>${stars(n)}</b>`;$('chestTap').classList.add('hidden');$('chestReveal').classList.remove('hidden');return}const p=c.tap[n]||0;$('tapStatus').innerHTML=`${l} TAP${l===1?'':'S'} LEFT · <b>${p}%</b> chance for ${n+1}★`;$('chestTap').textContent=`TAP TO UPGRADE · ${p}%`;$('chestTap').classList.remove('hidden');$('chestReveal').classList.add('hidden')}
async function buy(idx,free=false){const c=CHESTS[idx],a=read(),cost=free?0:c.price+Math.round(c.price*TAX);if(a.money<cost){toast2('Not enough in-game USD');return}a.money-=cost;a.opened=(a.opened||0)+1;write(a);$('shop').classList.add('hidden');$('chestOpen').classList.remove('hidden');setupOpeningUI();const big=$('bigChest');big.style.setProperty('--chest1',c.c1);big.style.setProperty('--chest2',c.c2);big.className='bigChest';$('rewardCard').classList.remove('show');$('chestContinue').classList.add('hidden');$('chestTap').classList.add('hidden');$('chestReveal').classList.add('hidden');$('chestOpeningLabel').textContent=c.name.toUpperCase();$('tapStatus').textContent='ROLLING STARTING STAR LEVEL...';for(let i=0;i<9;i++){setStarUI(1+Math.floor(Math.random()*5));$('openStars').classList.remove('bbRoll');void $('openStars').offsetWidth;$('openStars').classList.add('bbRoll');await sleep(80+i*12)}const st=+weighted(c.start);setStarUI(st);$('tapStatus').innerHTML=`STARTED AT <b>${stars(st)}</b>`;await sleep(450);active={chest:c,star:st,left:4};updateTap()}
async function attempt(){if(busy||!active||active.left<=0||active.star>=5)return;busy=true;const p=active.chest.tap[active.star]||0;active.left--;const big=$('bigChest');big.classList.add('shake');await sleep(700);big.classList.remove('shake');if(Math.random()*100<p){active.star++;flash();$('tapStatus').innerHTML=`<span class="bbTapSuccess">UPGRADED! ${stars(active.star)}</span>`;setStarUI(active.star)}else $('tapStatus').innerHTML=`<span class="bbTapFail">NO UPGRADE</span> · ${active.left} taps left`;await sleep(650);busy=false;updateTap()}
function choose(star,a){let rar=weighted(REWARD[star]),pool=ITEMS.filter(i=>!i.starter&&i.rarity===rar);let un=pool.filter(i=>!a.owned.includes(i.id));let picked=un.length?un[Math.floor(Math.random()*un.length)]:null,up=false;if(!picked&&star>=4){for(let z=R.indexOf(rar);z<R.length&&!picked;z++){const h=ITEMS.filter(i=>!i.starter&&i.rarity===R[z]&&!a.owned.includes(i.id));if(h.length){picked=h[Math.floor(Math.random()*h.length)];up=R[z]!==rar}}}let dup=false;if(!picked){picked=pool[Math.floor(Math.random()*pool.length)]||ITEMS.find(i=>!i.starter);dup=true}return {picked,dup,up}}
async function reveal(){if(busy||!active)return;busy=true;$('chestTap').classList.add('hidden');$('chestReveal').classList.add('hidden');$('tapStatus').textContent='REVEALING COSMETIC...';const big=$('bigChest');big.classList.add('shake');await sleep(750);big.classList.remove('shake');big.classList.add('open');flash();await sleep(430);const a=read(),r=choose(active.star,a),i=r.picked;$('rewardPreview').innerHTML=preview(i);$('rewardName').textContent=i.name;$('rewardRarity').className='rar '+i.rarity;$('rewardRarity').textContent=i.rarity.toUpperCase();let note=`${stars(active.star)} CHEST · `;if(r.dup){const refund=Math.round(active.chest.price*.35);a.money+=refund;note+='DUPLICATE · '+fmt(refund)+' REFUND'}else{a.owned.push(i.id);note+='NEW COSMETIC'+(r.up?' · DUPLICATE PROTECTION UPGRADE':'')}$('rewardNote').textContent=note;write(a);$('rewardCard').classList.add('show');$('chestContinue').classList.remove('hidden');busy=false}
function flash(){const f=$('chestFlash');f.classList.remove('go');void f.offsetWidth;f.classList.add('go')}
function sleep(ms){return new Promise(r=>setTimeout(r,ms))}
function toast2(t){const el=$('toast');if(!el)return;el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1500)}
function wire(){setupOpeningUI();const chestTab=document.querySelector('.tab[data-tab="chest"]');if(chestTab)chestTab.onclick=()=>{document.querySelectorAll('.tab').forEach(z=>z.classList.toggle('active',z===chestTab));renderChestShop()};const dbg=document.querySelector('[data-debug="chest5"]');if(dbg){dbg.textContent='Open Crown FREE';dbg.onclick=()=>buy(CHESTS.length-1,true)}const version=[...document.querySelectorAll('.tag')].find(e=>/CHEST ECONOMY|PUBLIC WEB VERSION/.test(e.textContent));if(version)version.textContent='LUCKY CHESTS v5';window.addEventListener('keydown',e=>{if(active&&['Space','KeyS','KeyC','KeyL','Escape'].includes(e.code)){e.preventDefault();e.stopImmediatePropagation()}},true)}
wire();
})();
