export class CombatFeedbackRenderer {
  constructor(ctx){this.ctx=ctx;this.tracers=[];this.impacts=[];this.damageNumbers=[];this.explosions=[];this.meleeSwings=[];this.hitmarkerTimer=0;this.hitmarkerCrit=false;}
  spawnShot({muzzle,end,hit,crit,type}){this.tracers.push({start:{...muzzle},end:{...end},life:type==='shotgun-pellet'?.055:.075,maxLife:type==='shotgun-pellet'?.055:.075,type});this.impacts.push({x:end.x,y:end.y,life:.12,maxLife:.12,hit,crit,type});}
  spawnLaunch(){} spawnProjectileImpact({point,type,hit,crit}){this.impacts.push({x:point.x,y:point.y,life:.18,maxLife:.18,hit,crit,type});} spawnExplosion({point,radius}){this.explosions.push({x:point.x,y:point.y,radius,life:.42,maxLife:.42});} spawnMeleeSwing({owner,range,angle}){this.meleeSwings.push({x:owner.x,y:owner.y,range,angle,life:.18,maxLife:.18});}
  spawnHit({point,damage,crit}){this.damageNumbers.push({x:point.x,y:point.y-8,damage:Math.round(damage),crit,life:.75,maxLife:.75});this.hitmarkerTimer=crit?.16:.11;this.hitmarkerCrit=crit;}
  update(dt){this.hitmarkerTimer=Math.max(0,this.hitmarkerTimer-dt);for(const item of[...this.tracers,...this.impacts,...this.damageNumbers,...this.explosions,...this.meleeSwings])item.life-=dt;for(const n of this.damageNumbers)n.y-=27*dt;this.tracers=this.tracers.filter(i=>i.life>0);this.impacts=this.impacts.filter(i=>i.life>0);this.damageNumbers=this.damageNumbers.filter(i=>i.life>0);this.explosions=this.explosions.filter(i=>i.life>0);this.meleeSwings=this.meleeSwings.filter(i=>i.life>0);}
  drawProjectiles(projectiles){const ctx=this.ctx;ctx.save();for(const p of projectiles){if(p.type==='sniper'){ctx.strokeStyle='rgba(174,233,255,.28)';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(p.x-Math.cos(p.angle)*34,p.y-Math.sin(p.angle)*34);ctx.lineTo(p.x,p.y);ctx.stroke();ctx.fillStyle='#dff8ff';ctx.beginPath();ctx.arc(p.x,p.y,3.2,0,Math.PI*2);ctx.fill();}else{ctx.strokeStyle='rgba(210,220,210,.30)';ctx.lineWidth=7;ctx.beginPath();ctx.moveTo(p.x-Math.cos(p.angle)*28,p.y-Math.sin(p.angle)*28);ctx.lineTo(p.x,p.y);ctx.stroke();ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.angle);ctx.fillStyle='#c89b49';ctx.beginPath();ctx.roundRect(-9,-4,18,8,4);ctx.fill();ctx.fillStyle='#7c4335';ctx.beginPath();ctx.moveTo(-8,-4);ctx.lineTo(-15,0);ctx.lineTo(-8,4);ctx.closePath();ctx.fill();ctx.restore();}}ctx.restore();}
  drawWorld(){const ctx=this.ctx;ctx.save();ctx.lineCap='round';for(const t of this.tracers){ctx.globalAlpha=t.life/t.maxLife;ctx.strokeStyle=t.type==='shotgun-pellet'?'#ffd99b':'#eaf7ff';ctx.lineWidth=t.type==='shotgun-pellet'?1:1.5;ctx.beginPath();ctx.moveTo(t.start.x,t.start.y);ctx.lineTo(t.end.x,t.end.y);ctx.stroke();}for(const e of this.explosions){const a=e.life/e.maxLife,r=e.radius*(.22+(1-a)*.78);ctx.globalAlpha=.28*a;ctx.fillStyle='#ffb94b';ctx.beginPath();ctx.arc(e.x,e.y,r*.52,0,Math.PI*2);ctx.fill();ctx.globalAlpha=.65*a;ctx.strokeStyle='#ffe29a';ctx.lineWidth=5;ctx.beginPath();ctx.arc(e.x,e.y,r*.68,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=.3*a;ctx.strokeStyle='#5b6a66';ctx.lineWidth=12;ctx.beginPath();ctx.arc(e.x,e.y,r*.9,0,Math.PI*2);ctx.stroke();}for(const s of this.meleeSwings){const a=s.life/s.maxLife;ctx.globalAlpha=.7*a;ctx.strokeStyle='#dff6ff';ctx.lineWidth=5;ctx.beginPath();ctx.arc(s.x,s.y,s.range*.58,s.angle-.75,s.angle+.75);ctx.stroke();}for(const i of this.impacts){const a=i.life/i.maxLife;ctx.globalAlpha=a;ctx.strokeStyle=i.hit?(i.crit?'#ffe577':'#b8f4ff'):'#d1dde3';ctx.lineWidth=i.crit?3:2;ctx.beginPath();ctx.arc(i.x,i.y,3+(1-a)*5,0,Math.PI*2);ctx.stroke();}ctx.textAlign='center';ctx.textBaseline='middle';for(const n of this.damageNumbers){const a=Math.min(1,n.life/.22);ctx.globalAlpha=a;ctx.font=n.crit?'900 18px ui-monospace,monospace':'900 14px ui-monospace,monospace';ctx.fillStyle=n.crit?'#ffe45f':'#f4fbff';ctx.strokeStyle='rgba(4,12,18,.88)';ctx.lineWidth=4;ctx.strokeText(`${n.damage}`,n.x,n.y);ctx.fillText(`${n.damage}`,n.x,n.y);}ctx.restore();}
  drawCrosshair(pointer,manager){const ctx=this.ctx,w=manager.currentWeapon();if(!w)return;const spread=manager.currentSpreadDegrees(),gap=w.kind==='melee'?11:7+spread*2.2,len=manager.isFullyADS()?7:8,x=pointer.x,y=pointer.y;ctx.save();ctx.strokeStyle='rgba(239,249,255,.94)';ctx.lineWidth=2;ctx.lineCap='round';for(const [x1,y1,x2,y2]of[[x-gap-len,y,x-gap,y],[x+gap,y,x+gap+len,y],[x,y-gap-len,x,y-gap],[x,y+gap,x,y+gap+len]]){ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();}ctx.restore();}
  drawHitmarker(pointer){if(this.hitmarkerTimer<=0)return;const ctx=this.ctx,x=pointer.x,y=pointer.y,a=Math.min(1,this.hitmarkerTimer/.08),inner=this.hitmarkerCrit?7:6,outer=this.hitmarkerCrit?15:13;ctx.save();ctx.globalAlpha=a;ctx.strokeStyle=this.hitmarkerCrit?'#ffe45f':'#fff';ctx.lineWidth=this.hitmarkerCrit?3:2;for(const sx of[-1,1])for(const sy of[-1,1]){ctx.beginPath();ctx.moveTo(x+sx*inner,y+sy*inner);ctx.lineTo(x+sx*outer,y+sy*outer);ctx.stroke();}ctx.restore();}
}
